### PR TITLE
feature: handle git dependencies

### PR DESCRIPTION
**Pull request by adrian-gierakowski**
- add git and cacert as deps to cacheDrvs
- use pkg.reference instead of version in package.json of isolated builds
  since it allow yarn to find the git repo (this will probably also fix
  oter type of deps)

### CODE REVIEW

**Comment by stephank** [comment]
Oh, I'm surprised that's all it took. The added dependencies are packages common enough that it should be fine.

Thanks for contributing! 👍

**Comment by stephank** [comment]
I'm afraid this broke the test we have in CI, which adds the plugin to this repo itself, then tries to do an isolated build of `sqlite3`: https://github.com/stephank/yarn-plugin-nixify/blob/01bf568bdc1de0792adb322c8831861d9b9adef6/.github/workflows/build.yml#L74-L89

The `nix-build` step output of that is:
```
these 4 derivations will be built:
  /nix/store/1p66rdlaj6zr6n5ja8p76ilwfilahf91-collect-cache.sh.drv
  /nix/store/lnyaj1kz067ymaixf09x8j3cpbazk59y-collect-cache.sh.drv
  /nix/store/9fhxsdfnxrjm932mwm0nl6ybsd3crzka-sqlite3-5.0.2.drv
  /nix/store/hdlywkqh8pv0n4ydhb492nr1jsm4jl2i-yarn-plugin-nixify.drv
these 2 paths will be fetched (0.80 MiB download, 2.16 MiB unpacked):
  /nix/store/3pj61q16c2cmivip0lrf45bpdybs0w0r-sqlite-3.37.0-dev
  /nix/store/g2pigzz84n531ra2q56ln9x25xbxrgs6-sqlite-3.37.0-bin
building '/nix/store/1p66rdlaj6zr6n5ja8p76ilwfilahf91-collect-cache.sh.drv'...
copying path '/nix/store/g2pigzz84n531ra2q56ln9x25xbxrgs6-sqlite-3.37.0-bin' from 'https://cache.nixos.org'...
copying path '/nix/store/3pj61q16c2cmivip0lrf45bpdybs0w0r-sqlite-3.37.0-dev' from 'https://cache.nixos.org'...
building '/nix/store/lnyaj1kz067ymaixf09x8j3cpbazk59y-collect-cache.sh.drv'...
building '/nix/store/9fhxsdfnxrjm932mwm0nl6ybsd3crzka-sqlite3-5.0.2.drv'...
building
➤ YN0000: ┌ Resolution step
➤ YN0001: │ Error: Assertion failed: calling "bindDescriptor" on a virtual descriptor is unsupported
    at Fg.bindDescriptor (/nix/store/liggs6jpg4lbm700jvdpyqlk2ja66xi8-yarn-3.1.1.cjs:432:8107)
    at pd.bindDescriptor (/nix/store/liggs6jpg4lbm700jvdpyqlk2ja66xi8-yarn-3.1.1.cjs:432:5076)
    at pd.bindDescriptor (/nix/store/liggs6jpg4lbm700jvdpyqlk2ja66xi8-yarn-3.1.1.cjs:432:5076)
    at I (/nix/store/liggs6jpg4lbm700jvdpyqlk2ja66xi8-yarn-3.1.1.cjs:441:6932)
    at async Promise.all (index 0)
    at async Ke.resolveEverything (/nix/store/liggs6jpg4lbm700jvdpyqlk2ja66xi8-yarn-3.1.1.cjs:441:8197)
    at async /nix/store/liggs6jpg4lbm700jvdpyqlk2ja66xi8-yarn-3.1.1.cjs:444:2138
    at async Fe.startTimerPromise (/nix/store/liggs6jpg4lbm700jvdpyqlk2ja66xi8-yarn-3.1.1.cjs:412:3730)
    at async Ke.install (/nix/store/liggs6jpg4lbm700jvdpyqlk2ja66xi8-yarn-3.1.1.cjs:444:2077)
    at async /nix/store/liggs6jpg4lbm700jvdpyqlk2ja66xi8-yarn-3.1.1.cjs:486:14900
➤ YN0000: └ Completed
➤ YN0000: Failed with errors in 0s 43ms
error: builder for '/nix/store/9fhxsdfnxrjm932mwm0nl6ybsd3crzka-sqlite3-5.0.2.drv' failed with exit code 1
error: 1 dependencies of derivation '/nix/store/hdlywkqh8pv0n4ydhb492nr1jsm4jl2i-yarn-plugin-nixify.drv' failed to build
```

The `mkIsolatedBuild` call contains: `reference = "virtual:..."`

**Comment by adrian-gierakowski** [comment]
I’ll investigate tomorrow. I wonder why it would be virtual btw. I guess a temporary solution would be to strip the virtual prefix as the behaviour would be no different then before the change in this case, while it would still work with git deps.

**Comment by adrian-gierakowski** [comment]
Just reading the code from my phone, but maybe we need to call this?

https://github.com/yarnpkg/berry/blob/e64af835177f64fc4820f1bb582e0f918b73ebfc/packages/yarnpkg-core/sources/structUtils.ts#L203

**Comment by stephank** [comment]
Ah, of course. There's already a devirtualized `devirtPkg` in scope there, so it was a one line change:

https://github.com/stephank/yarn-plugin-nixify/commit/c999d4070cf463758198868b824ea5e549e9622d#diff-0e9ffa40772b7eca15b8e9fed0a847258c6a80dca2f41d5ddc0cb70357736f2cR248

Works now! 👍

**Pull request merged**
